# GitHub Actions workflow to build and push Docker image to Docker Hub
# Save this file as .github/workflows/docker-publish.yml

name: Build and Push Docker image to Docker Hub


on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag (e.g. 1.0.0, latest)'
        required: false
        default: 'latest'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64]
        include:
          - arch: amd64
            platform: linux/amd64
            appimage_url: https://affirmatech.com/download/meshsense/meshsense-x86_64.AppImage
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download and extract AppImage
        run: |
          sudo apt-get update && sudo apt-get install -y fuse
          curl -sSL ${{ matrix.appimage_url }} -o meshsense.AppImage
          chmod +x meshsense.AppImage
          ./meshsense.AppImage --appimage-extract
          mv squashfs-root meshsense-extracted

      - name: Prepare build context
        run: |
          mkdir -p build-context
          cp -r meshsense-extracted build-context/meshsense
          cp -r * build-context/ || true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image for ${{ matrix.platform }}
        uses: docker/build-push-action@v5
        with:
          context: build-context
          push: true
          platforms: ${{ matrix.platform }}
          tags: bajotumn/meshsense:${{ github.event.inputs.tag || 'latest' }}
